### ISSUE TITLE
become a github verified publisher

### ISSUE THREAD

**Issue by ndeloof** [LambdaTest/LambdaTest-tunnel-action#22]
My company uses github action allowlist so we don't use random actions in our automation.
verified publisher are approved by default.
could you please consider https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization ?

**Comment by psych0der** [comment]
Hey @ndeloof, LambdaTest tunnel action is verified. I hope this helps.
