### ISSUE TITLE
Add a new parameter use-private-ip

### ISSUE THREAD

**Issue by nboopathy** [LambdaTest/LambdaTest-tunnel-action#45]
When we use LambdaTest/LambdaTest-tunnel-action@v2 to create tunnel, we need to be able to pass parameter use-private-ip. Currently our tests are geolocation based so we need this parameter to be added otherwise our tests are failing

**Expected**: docker run --name=8dab6f707fda3fdbfb42 -d=true --net=host lambdatest/tunnel:latest --user user --key key --tunnelName "playwright" --shared-tunnel -v --load-balanced **--use-private-ip** --controller github --infoAPIPort 46163

**Actual**: docker run --name=8dab6f707fda3fdbfb42 -d=true --net=host lambdatest/tunnel:latest --user user --key key --tunnelName "playwright" --shared-tunnel -v --load-balanced --controller github --infoAPIPort 46163

**Comment by vipulkv** [comment]
@nboopathy Sure. We are prioritising this. We will update on this soon. cc @ankur-lambdatest

**Comment by vipulkv** [comment]
We have released the new version of Tunnel Action which has a support of `--use-private-ip` flag. https://github.com/LambdaTest/LambdaTest-tunnel-action/releases/tag/v2.0.1

**Comment by nboopathy** [comment]
@vipulkv thank you
